Validacao por hora
ninaai517/partida-futebol-api pull request #12
Opened 2023-11-22 18:06 UTC by ninaai517

2023-11-22 18:06 UTC, ninaai517 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validação - Por horário](https://trello.com/c/fTLjDPgX/7-valida%C3%A7%C3%A3o-por-hor%C3%A1rio)

2023-11-23 12:54 UTC, silasyudi requested changes

2023-11-23 12:54 UTC, silasyudi commented on partida-futebol-api/src/main/java/br/com/meli/partidafutebolapi/service/PartidaService.java
> +        for(LocalDateTime data : datas){
A validação da hora não precisa de comparação com todas as partidas já registradas. Basta validar apenas o DTO.

2023-11-23 12:54 UTC, silasyudi commented on partida-futebol-api/src/main/java/br/com/meli/partidafutebolapi/service/PartidaService.java
> +                if(hr < 8 || hr > 22) {
O horário pode ser 22h00, mas não pode ser após às 22h00, por exemplo, 22h01 já seria inválido.

2023-11-24 21:12 UTC, closed without merging