Validacao valor negativo nos metodos POST e PUT
ninaai517/partida-futebol-api pull request #6
Opened 2023-11-10 21:47 UTC by ninaai517

Placar dos times nao pode receber valor negativo e nem ser nulo.

2023-11-10 21:48 UTC, ninaai517 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validação - Resultado inválido](https://trello.com/c/Nyr3Rhxo/12-valida%C3%A7%C3%A3o-resultado-inv%C3%A1lido)

2023-11-13 12:20 UTC, silasmeli requested changes

2023-11-13 12:20 UTC, silasmeli commented on partida-futebol-api/src/main/java/br/com/meli/partidafutebolapi/service/BuscaService.java
> +                filter(partida -> (partida.getGoalsMandante() - partida.getGoalsVisitante()) >= 3).
Esse algoritmo vai falhar quando o visitante fizer uma goleada. Exemplo:

Mandante 0 x 3 Visitante = -3

É goleada, mas não vai passar na sua validação. Procure uma forma de pegar o valor absoluto da expressão.

2023-11-13 12:20 UTC, silasmeli commented on partida-futebol-api/src/main/java/br/com/meli/partidafutebolapi/model/Partida.java
> +    @PositiveOrZero
Essas validações devem estar no DTO, pois é ele quem é validado na controller.

2023-11-13 13:34 UTC, silasmeli approved these changes

2023-11-13 13:39 UTC, closed without merging